CREATE TABLE bands (
id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY, 
name VARCHAR(225) NOT NULL 
);

CREATE TABLE album (
id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
name VARCHAR(225) NOT NULL,
band_id INT NOT NULL REFERENCES bands(id) ON DELETE CASCADE
);

ALTER TABLE album 
ADD release_year INT;